services:

  json-server:
    image: vimagick/json-server
    command: -h 0.0.0.0 -p 3000 db.json
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    restart: always

  test-mosaic:
    image: test-mosaic
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3000

networks:
  dev-network:
    driver: bridge
